## NUMPY

In [2]:
!pip install numpy  # Installs numpy library from pip

In [2]:
import numpy as np  # Import numpy library with alias np to access numpy functions with np

In [4]:
np.absolute(-5)  # Outputs absolute value

5

In [6]:
# Numpy Arrays

a = np.array([1,3,5,7]) # declares numpy array
print(a)

[1 3 5 7]


In [9]:
print(type(a)) # Outputs the type of a variable

<class 'numpy.ndarray'>


In [12]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])  # Declares 2D array
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
print(a.shape)
print(b.shape)

# .shape function is used to output the dimension

(4,)
(2, 5)


In [13]:
b.T # .T outputs the transpose of matrix

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [16]:
print(np.dot(b,b.T)) # Results the dot product 'Multiplication of Matrix'
print(b.dot(b.T))

[[ 55 130]
 [130 330]]
[[ 55 130]
 [130 330]]


In [16]:
np.random.randint(10,87,10) 
# Generates a random numpy array of size 10 b/w 10(inclusive) and 87(exclusive)

array([30, 63, 85, 17, 35, 67, 34, 24, 27, 16])

In [27]:
## Tensor is more than 2 axes

matrix = np.random.randint(10,87,(10,5))
print(matrix,type(matrix))
# Generates a random numpy array of size 10x5 b/w 10(inclusive) and 87(exclusive)

[[49 76 85 86 68]
 [50 82 28 20 43]
 [79 31 45 47 42]
 [34 16 50 12 85]
 [78 48 70 55 73]
 [70 39 33 74 70]
 [64 26 67 69 80]
 [75 32 10 82 54]
 [11 10 42 69 29]
 [78 66 29 86 22]] <class 'numpy.ndarray'>


In [20]:
np.min(matrix) # minimum element in matrix

11

In [45]:
a = np.array([2,51,56,10,5,-33,56,10,99,39,51,2,56])
print(a)

[  2  51  56  10   5 -33  56  10  99  39  51   2  56]


In [32]:
np.argmin(a) # Returns the index of min element in array

3

In [34]:
np.unique(a) # Returns Unique List of Array 'a'(in this case) in sorted order

array([-33,   2,   5,  10,  39,  51,  56,  99])

In [46]:
c = np.unique(a,return_counts=True) # Return unique list but also with their freq
print(c)

(array([-33,   2,   5,  10,  39,  51,  56,  99]), array([1, 2, 1, 2, 1, 2, 3, 1], dtype=int64))


In [47]:
print(c[0])
print(type(c))
print(type(c[0]))

[-33   2   5  10  39  51  56  99]
<class 'tuple'>
<class 'numpy.ndarray'>


In [38]:
print(c[1])

[1 2 1 2 1 1 2 1]


In [41]:
# Program to find out the Number with Highest Frequency in array

In [48]:
index = np.argmax(c[1]) # Gives index of highest freq of any number
element = c[0][index] # Returns the Element with highest occurence 
print(element)
# print(index)

56


In [49]:
# Slicing Arrays

matrix

array([[49, 76, 85, 86, 68],
       [50, 82, 28, 20, 43],
       [79, 31, 45, 47, 42],
       [34, 16, 50, 12, 85],
       [78, 48, 70, 55, 73],
       [70, 39, 33, 74, 70],
       [64, 26, 67, 69, 80],
       [75, 32, 10, 82, 54],
       [11, 10, 42, 69, 29],
       [78, 66, 29, 86, 22]])

In [50]:
print(matrix[2:4,1:5])

[[31 45 47 42]
 [16 50 12 85]]


In [51]:
matrix[0,0]

49

In [7]:
## Different Matrices

x = np.zeros((2,3))  # Creates a zero matrix of specified order
y = np.ones((4,5))  # Creates a Ones matrix of specified order
z = np.eye(3)  # Creates identity matrix of specified order => Square Matrix

w = np.full((2,4),8)  # Creates a constant matrix with specified constant of specified order

print("Zero matrix  \n", x)

print("Ones matrix  \n",y)

print("Identity matrix  \n",z)

print("Constant matrix  \n",w)


Zero matrix  
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones matrix  
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Identity matrix  
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Constant matrix  
 [[8 8 8 8]
 [8 8 8 8]]


In [9]:
## Arithmetic Operations

x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

# Element Wise Operations

print(x+y)
print(np.add(x,y))

print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))

print(x/y)
print(np.divide(x,y))

print(np.sqrt(x)) ## Returns array of square root of elements

[ 7  9 11 13 15]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [18]:
## Multiplication/Dot Product of Vectors = Scalar

print(x)
print(y)

print(np.dot(x,y)) # Results Scalar entity

[1 2 3 4 5]
[ 6  7  8  9 10]
130


In [43]:
## Sum along axises
d1 = np.array([31,22,34,65,6])
d2 = np.array([[1,2,3],[4,5,6]])
print(d2)

print("Linear Sum: ",sum(d1)) # Sum of all elements in d1 array
print("Linear Sum of 2D: ",np.sum(d2)) # Sum of elements in d2 2D array

print("Vertical Sum: ",np.sum(d2,axis=0)) # Sum of elements along vertical axis
print("Horizontal Sum: ",np.sum(d2,axis=1)) # Sum of elements along horizontal axis

[[1 2 3]
 [4 5 6]]
Linear Sum:  158
Linear Sum of 2D:  21
Vertical Sum:  [5 7 9]
Horizontal Sum:  [ 6 15]


In [36]:
## Stacking of Arrays

print(x,y)

# Note: axis by default is 0 and stack vertically
# axis = 0 => Stacks Vertically
# axis = 1 => Stacks Horizontally

print(np.stack((x,y),axis=0)) # Stacks specified arrays vertically
print(np.stack((x,y),axis=1)) # Stacks specified arrays horizontally

[1 2 3 4 5] [ 6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [48]:
## Reshape a Numpy Array

print("Original: \n",d2)
print("Shape: ",d2.shape)  # has 6 elements, try to reshape so every element get its place

d1 = d2.reshape((3,2))  # Reshapes 2x3 array into 3x2 array
d1 = d2.reshape((-1,2))  # calculates no. of rows automatically when col is provided 
d1 = d2.reshape((3,-1))  # calculates no. of cols automatically when rows is provided
d1 = d2.reshape((6,))  # Reshapes 2x3 array into linear array
d1 = d2.reshape((6,1))  # Reshapes 2x3 array into 6x1 array
print("Reshaped: \n",d1)

Original: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Reshaped: 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [52]:
arr = np.arange(10)+7  # Creates an array with given range

print(arr)

[ 7  8  9 10 11 12 13 14 15 16]


## Numpy Random Module
- random: returns random float values in interval [0.0,1.0)
- rand: Return random value in provided shape
- randn: Returns values from standard normal distribution in provided shape
- randint: Returns an array with provided no. of elements(10) in provided range (2,9)
- choice: Returns a random element from the given array
- shuffle: Randomly shuffles the elements of given array

In [57]:
np.random.shuffle(arr)  # Randomly shuffles the elements of given array
print(arr)

[ 8  9 16 12 11 15  7 13 14 10]


In [58]:
np.random.rand(2,3)  # Return random value in provided shape

array([[0.19621659, 0.00477666, 0.30012378],
       [0.55753521, 0.06361974, 0.58927142]])

In [59]:
np.random.randn(2,3)  
# Returns values from standard normal distribution in provided shape

array([[-2.11471418, -0.58050032,  0.16620375],
       [-0.33329885, -0.01901488,  2.82669622]])

In [60]:
np.random.randint(2,9,10) 
# Returns an array with provided no. of elements(10) in provided range (2,9)

array([7, 4, 2, 8, 8, 3, 7, 3, 2, 6])

In [63]:
random_array_element = np.random.choice(arr)
print(random_array_element)

# Returns a random element from the given array

14


In [64]:
np.random.seed(5) # Sets a seed value to get similar set of values

## More Functions in Numpy
- mean
- average
- standard deviation
- variation

In [69]:
a = np.array([[1,23,4,5,6],[22,3,55,32,43]])
b = np.array([28,8,6,5,7])

print(a)
print(b)

[[ 1 23  4  5  6]
 [22  3 55 32 43]]
[28  8  6  5  7]


In [76]:
# MEAN
mean = sum(b)/len(b)
print(mean)

#Inbuilt Numpy Function for MEAN
print(np.mean(b))

# Mean Along axis
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

10.8
10.8
[11.5 13.  29.5 18.5 24.5]
[ 7.8 31. ]


In [77]:
# Average

# .average() function computes the weighted average of elements in an array according to their respective weight given in another array. The function can have an axis parameter. If the axis is not specified, the array is flattened.

w = np.array([2,3,4,5,6])

print(np.average(b,weights=w))

8.55


In [82]:
# Standard Deviation
u = np.mean(b)
stnd = np.sqrt(np.mean((abs(b-u)**2)))
print(stnd)

# Inbuilt Numpy Function for Standard Deviation
print(np.std(b))

8.657944328765346
8.657944328765346


In [83]:
# Variance
variance = stnd**2
print(variance)

# Inbuilt Numpy Function for Variance
print(np.var(b))

74.96000000000002
74.96000000000001
